spring:
  application:
    name: Product-Service
  cache:
    type: redis
    cache-names: redis-cache
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    url: jdbc:postgresql://localhost:5432/avanza_natural
    user: postgres
    password: password
    baseline-on-migrate: true
    default-schema: products
  datasource:
    url: jdbc:postgresql://localhost:5432/avanza_natural
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      max-file-size: 1MB
server:
  port: 7070
aws:
  bucket:
    name:
  region: ru-1
  credentials:
    access-key:
    secret-key:

web:
  service:
    uri: http://localhost:3000

resilience4j.ratelimiter:
  instances:
    productLimiter:
      limitForPeriod: 30
      limitRefreshPeriod: 1s
    categoryLimiter:
      limit-for-period: 30
      limitRefreshPeriod: 1s
    subcategoryLimiter:
      limit-for-period: 30
      limitRefreshPeriod: 1s
    productTypeLimiter:
      limit-for-period: 30
      limitRefreshPeriod: 1s