spring:
  application:
    name: Product-Service
  cache:
    type: redis
    cache-names: redis-cache
  data:
    redis:
      host: localhost
      password: passwordForRedis
      port: 6379
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    url: jdbc:postgresql://localhost:5432/avanza_natural #изменить на product
    user: postgres
    password: password
    baseline-on-migrate: true
  datasource:
    url: jdbc:postgresql://localhost:5432/avanza_natural
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      max-file-size: 40MB
server:
  port: 7070
aws:
  bucket:
    name: avanzanaturale
  region:
    static: eu-south-2
  credentials:
    access-key:
    secret-key: