create table if not exists Categories(
    id int generated by default as identity primary key ,
    title varchar(40) not null unique,
    image varchar
);

create table if not exists Subcategories(
    id int generated by default as identity primary key ,
    category_id int references Categories(id) on delete cascade,
    title varchar(40) not null,
    image varchar
);

create table if not exists Products_Types(
    id int generated by default as identity primary key ,
    subcategory_id int references Subcategories(id) on delete cascade ,
    title varchar(40) not null,
    image varchar
);

create table if not exists Products(
    id int generated by default as identity primary key ,
    title varchar(60) not null ,
    brand varchar(60) not null ,
    description varchar(1000) ,
    price float not null ,
    in_stock boolean not null,
    category_id int references Categories(id) on delete set null ,
    subcategory_id int references Subcategories(id) on delete set null ,
    product_type_id int references Products_Types(id) on delete set null
);

-- this is for tests
insert into Categories(title, image) values ('Water','Image');
insert into Categories(title, image) values ('Chocolate','Image');
insert into Categories(title, image) values ('Meat','Image');
insert into Categories(title, image) values ('Clothes', 'Image');

insert into Subcategories(category_id, title, image) values (4,'T-shirts','Image');
insert into Subcategories(category_id, title, image) values (4,'Skirts','Image');
insert into Subcategories(category_id, title, image) values (4,'Trousers','Image');

insert into Products_Types(subcategory_id, title, image) values (1,'Orange T-Shirt','Image');
insert into Products_Types(subcategory_id, title, image) values (1,'Blue T-Shirt','Image');
insert into Products_Types(subcategory_id, title, image) values (1,'Ping T-Shirt','Image');

insert into Products(title, brand, description, price, in_stock, category_id, subcategory_id, product_type_id) values ('First Product', 'brand', 'description',19.9,true,4,1,1);
insert into Products(title, brand, description, price, in_stock, category_id, subcategory_id, product_type_id) values ('Second Product', 'brand', 'description',19.9,true,4,1,1)