create schema if not exists products;

create table if not exists products.category(
    id int generated by default as identity primary key ,
    title varchar(40) not null unique,
    image varchar
);

create table if not exists products.subcategory(
    id int generated by default as identity primary key ,
    category_id int references products.category(id) on delete cascade,
    title varchar(40) not null,
    image varchar
);

create table if not exists products.product_type(
    id int generated by default as identity primary key ,
    subcategory_id int references products.subcategory(id) on delete cascade ,
    title varchar(40) not null,
    image varchar
);

create table if not exists products.product(
    id int generated by default as identity primary key ,
    title varchar(60) not null ,
    brand varchar(60) not null ,
    description varchar(1000) ,
    price float not null ,
    in_stock boolean not null,
    category_id int references products.category(id) on delete cascade,
    subcategory_id int references products.subcategory(id) on delete cascade,
    product_type_id int references products.product_type(id) on delete cascade
);