create table if not exists Categories(
    id int generated by default as identity primary key ,
    product_id int references Products(id),
    title varchar(40) not null unique
);


create table if not exists Products(
    id int generated by default as identity primary key ,
    title varchar(100) not null ,
    description varchar(1000) ,
    price float not null ,
    in_stock boolean not null
);

create table if not exists Products_Types(
    id int generated by default as identity primary key ,
    product_id int references Products(id),
    title varchar(50) not null
);

create table if not exists Subcategories(
    id int generated by default as identity primary key ,
    product_id int references Products(id),
    title varchar(50) not null
)